ALTER TABLE "ProductItem"
  ALTER COLUMN "price" SET DATA TYPE INTEGER USING ROUND("price" * 100)::INTEGER;

ALTER TABLE "Ingredient"
  ALTER COLUMN "price" SET DATA TYPE INTEGER USING ROUND("price" * 100)::INTEGER;

ALTER TABLE "Cart"
  ALTER COLUMN "totalAmount" SET DATA TYPE INTEGER USING ROUND("totalAmount" * 100)::INTEGER,
  ALTER COLUMN "totalAmount" SET DEFAULT 0;

ALTER TABLE "Order"
  ALTER COLUMN "totalAmount" SET DATA TYPE INTEGER USING ROUND("totalAmount" * 100)::INTEGER;
